export enum ErrorCode {
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    BAD_MESSAGE = 'BAD_MESSAGE',
    SYNTAX_ERROR = 'SYNTAX_ERROR',
    REPOSITORY_ERROR = 'REPOSITORY_ERROR',
    PUBSUB_ERROR = 'PUBSUB_ERROR',
    FST_ERR_VALIDATION = 'FST_ERR_VALIDATION',
}

export enum StatusCode {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    PRECONDITION_FAILED = 412,
    I_AM_A_TEAPOT = 418,
    UNPROCESSABLE_ENTITY = 422,
    FAILED_DEPENDENCY = 424,
    TOO_EARLY = 425,
    PRECONDITION_REQUIRED = 428,
    INTERNAL_ERROR = 500,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
}

export enum PostgresErrorCode {
    RAISE_EXCEPTION = 'P0001',
    UNIQUE_VIOLATION = '23505',
    CHECK_VIOLATION = '23514',
    NOT_NULL_VIOLATION = '23502',
    UNDEFINED_FUNCTION = '42883',
    UNDEFINED_TABLE = '42P01',
    UNDEFINED_PARAMETER = '42P02',
    UNDEFINED_OBJECT = '42704',
    UNDEFINED_COLUMN = '42703',
    QUERY_CANCELED = '57014',
    CONNECTION_REFUSED = 'ECONNREFUSED',
}
